
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zaizrscurbgnvpvuxzlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaXpyc2N1cmJnbnZwdnV4emx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Mzc0MTgsImV4cCI6MjA2NzUxMzQxOH0.4-C7kp0woj-vmL_I-KAXpfkOjVSdyDx6vHwk5AbjMJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
